### ISSUE TITLE
No support for locations?

### ISSUE THREAD

**Issue by zpelli3** [archivesspace-labs/ArchivesSnake#30] opened 2019-10-30 14:41 UTC
I'm trying to create a script that, in part, lists all of the shelf locations of a collection. However I noticed that invoking repo.location does not work. Are there any plans to add functionality for querying locations? I don't see a way to do this using ArchivesSnake alone.

**Comment by gwiedeman** [comment] 2020-02-03 20:35
Sorry, @zpelli3 I just saw this. Thanks for the question! I think locations does work in the abstraction layer, but locations are not tied to repositories, so you just need to call then from the `ASpace()` object like so:

```
from asnake.aspace import ASpace

aspace = ASpace()
thing = aspace.locations(5)

print (thing)
```

Is this helpful?

**Comment by pobocks** [comment] 2020-02-03 23:29
@zpelli3 Additionally, if you're looking for locations related to a specific collection, I think going from the locations is probably the wrong way round - I think (@gwiedeman correct me if I'm wrong) you would have to walk the resource's tree, get containers the AOs are in, and get the locations off those containers?

**Comment by pobocks** [comment] 2020-02-03 23:48
If it's a published resource, this would be my starting point:

https://archivesspace.github.io/archivesspace/api/#get-top-containers-linked-to-a-published-resource-and-published-archival-ojbects-contained-within

This should be "ids of all locations in a resource":

```python
loc_ids = set()
for tc in x.resources(9000).top_containers:
    for loc in tc.container_locations:
        loc_ids.add(loc.id)
# at this point, loc_ids is a set of all relevant location ids
```

If not published, you could walk the tree of the record to get the same info, this will definitely be slower but it works:

```python
loc_ids = set()
for thing in x.resources(9000).tree.walk:
    for inst in thing.instances:
        # digital objects don't (I think) have sub_container values
        if inst.json().get('sub_container', False):
            for loc in inst.sub_container.top_container.container_locations:
                loc_ids.add(loc.id)
# at this point, loc_ids is once more a set of all relevant location ids
```

**Comment by pobocks** [comment] 2020-02-04 00:02
I'm going to close this, since it's not a bug and I don't think it's concretely specified enough to be a feature (and might be better served by adding some API routes on the ASpace side tbh), but I'm going to add "location handling" to a list of "things we might want to implement helpers/utilities for," also calling this to the attention of @helrond and @p-galligan )

**Closed as completed by pobocks** 2020-02-04 00:02 UTC
